### ISSUE TITLE
Offline package not configured correctly

### ISSUE THREAD

**Issue by atmoio** [ceiphr/sn-overcast-theme#2]
Nice work on the theme! You'll notice that in package.json there's a key `sn.main` with a value of `dist/dist.css`. This directory needs to exist in the [archive download](https://github.com/ceiphr/sn-overcast-theme/archive/v1.1.zip) for the theme to work in desktop. Or change that value to be the location of your main css file. Once you do that create a new version release.

**Comment by ceiphr** [comment]
`dist` was being gitignored, now it is included in the repo (https://github.com/ceiphr/sn-overcast-theme/commit/cfd26b3d53d086d21eb2be44aa94d3f24d4f6e0e). This fix is now in release [v1.1.1](https://github.com/ceiphr/sn-overcast-theme/tree/v1.1.1) and the installation link has been updated. The theme now works in desktop, thank you.
